### PR TITLE
Clarify that a success is needed to advance

### PR DESCRIPTION
**Pull request by ohexter**

### CODE REVIEW

**Comment by ohexter** [comment]
Hmm, the wording is actually quite awkward here because the existing 9p2+ uses 'result' as a singular in a different context than I am trying to express in the new addition. Any drafting suggestions welcomed.

**Comment by lgarron** [comment]
> Hmm, the wording is actually quite awkward here because the existing 9p2+ uses 'result' as a singular in a different context than I am trying to express in the new addition. Any drafting suggestions welcomed.

We use "recorded result" in some places, maybe that?

**Comment by CarterKoala** [comment]
Perhaps it is better as a subregulation of 9p3? Since this wouldn't be relevant unless 9p3 is being used

Something like:

`9p3a) Competitors with only DNF or DNS results are not eligible to advance.`

**Comment by ohexter** [comment]
Moved to 9p4, while technically only relevant under 9p3 that's due to the subtle Manchester Blind Off interaction that won't be readily apparent to readers.

**Pull request merged**
